import {test,expect} from '@playwright/test';
const pattern='arrays-hashing-lookup-counting-frequency-signatures';
test('diagnostic opens solutions without answering, revises ratings, and reports exact pattern familiarity',async({page},info)=>{
 await page.goto(`/#/diagnostic?topic=${pattern}`);
 await expect(page.getByRole('heading',{name:'How familiar does it feel?'})).toBeVisible();
 await page.getByRole('button',{name:'Start diagnostic test',exact:true}).click();
 await expect(page.getByRole('button',{name:/Definitely got it/})).toBeDisabled();
 await expect(page.getByLabel('Solution draft')).toHaveCount(0);
 await page.getByRole('button',{name:'Open solution set',exact:true}).click();
 await expect(page.getByLabel('Diagnostic solution code 1')).toContainText('sorted');
 await page.getByRole('button',{name:/Probably got it/}).click();
 await expect(page.getByRole('status')).toContainText('Saved: Probably got it');
 await page.getByRole('button',{name:/Definitely got it/}).click();
 await expect(page.getByRole('button',{name:/Definitely got it/})).toHaveAttribute('aria-pressed','true');
 const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('pattern-atlas.progress.v1')!));
 expect(saved.familiarity[`49:${pattern}`].rating).toBe('definitely');expect(saved.cards).toEqual({});expect(saved.activity).toEqual({});
 await page.screenshot({path:`artifacts/diagnostic-${info.project.name}.png`,fullPage:true});
 await page.getByRole('button',{name:'View diagnostic summary'}).click();
 await expect(page.getByRole('heading',{name:'Your familiarity snapshot'})).toBeVisible();
 await page.getByRole('link',{name:'View familiarity dashboard'}).click();
 const panel=page.getByLabel('Diagnostic familiarity',{exact:true});await expect(panel).toContainText('1 of 200 solution sets assessed');
 await page.getByLabel('Group familiarity by').selectOption('leaves');await page.getByLabel('Find a concept or pattern').fill('Frequency signatures');
 await expect(panel.locator('.familiarity-row')).toHaveCount(1);await expect(panel.locator('.familiarity-row')).toContainText('1 definitely');
 await page.reload();await expect(panel).toContainText('1 of 200 solution sets assessed');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.goto(`/#/diagnostic?topic=${pattern}`);await expect(page.getByRole('button',{name:'Start diagnostic test',exact:true})).toBeDisabled();
 await page.getByLabel('Diagnostic selection').selectOption('all');await page.getByRole('button',{name:'Start diagnostic test',exact:true}).click();
 await page.getByRole('button',{name:'Open solution set',exact:true}).click();await page.getByRole('button',{name:/Did not get it/}).click();
 await expect(page.getByRole('status')).toContainText('Saved: Did not get it');
});
test('diagnostic keeps its session stable, permits skipping and supports uncertainty-only reassessment',async({page})=>{
 await page.goto('/#/diagnostic');await page.getByLabel('Diagnostic length').selectOption('10');
 await page.getByRole('button',{name:'Start diagnostic test',exact:true}).click();
 const first=await page.locator('.diagnostic-card h2').textContent();
 await page.getByRole('button',{name:'Open solution set',exact:true}).click();await page.getByRole('button',{name:/Probably got it/}).click();
 await page.getByRole('button',{name:'Next set',exact:true}).click();await expect(page.locator('.diagnostic-session-bar')).toContainText('Set 2 of 10');
 await page.getByRole('button',{name:'Skip for now',exact:true}).click();await expect(page.locator('.diagnostic-session-bar')).toContainText('Set 3 of 10');
 await page.getByRole('button',{name:'Previous set',exact:true}).click();await page.getByRole('button',{name:'Previous set',exact:true}).click();await expect(page.locator('.diagnostic-card h2')).toHaveText(first!);
 await page.getByRole('button',{name:'Finish diagnostic',exact:true}).click();await expect(page.getByLabel('Diagnostic rating totals')).toContainText('9Unassessed');
 await page.goto('/#/diagnostic?mode=uncertain');await expect(page.locator('.diagnostic-setup')).toContainText('1 eligible solution sets');
});
