import {useMemo,useState} from 'react';
import {Select} from './Select';
import {accepted,activitySummary,utcDay,type Curriculum,type Progress} from '@pattern-atlas/core';

const displayDay=(key:string)=>new Date(`${key}T12:00:00Z`).toLocaleDateString('en',{weekday:'long',month:'long',day:'numeric',year:'numeric',timeZone:'UTC'});
export function ActivityHeatmap({data,progress}:{data:Curriculum;progress:Progress}){
  const currentYear=new Date().getUTCFullYear();
  const years=useMemo(()=>[...new Set([currentYear,...Object.keys(progress.leetcode?.calendars??{}).map(Number),...Object.values(progress.leetcode?.submissions??{}).map(s=>new Date(s.timestamp).getUTCFullYear())])].sort((a,b)=>b-a),[progress.leetcode,currentYear]);
  const [year,setYear]=useState(currentYear),[selected,setSelected]=useState('');
  const summary=useMemo(()=>activitySummary(progress.leetcode,year),[progress.leetcode,year]);
  const start=new Date(Date.UTC(year,0,1)),end=new Date(Date.UTC(year+1,0,1)),gridStart=new Date(start);gridStart.setUTCDate(start.getUTCDate()-(start.getUTCDay()+6)%7);
  const cells:Date[]=[];for(let day=new Date(gridStart);day<end||day.getUTCDay()!==1;day.setUTCDate(day.getUTCDate()+1))cells.push(new Date(day));
  const dayEntries=[...(summary.byDay[selected]??[])].sort((a,b)=>b.timestamp.localeCompare(a.timestamp)),dayTotal=summary.counts[selected]??0;
  const worked=new Map(data.problems.map(problem=>[problem.slug,problem.id]));
  return <section className="activity-panel" aria-label="LeetCode activity">
    <div className="section-heading"><div><p className="eyebrow">LEETCODE ACTIVITY · UTC</p><h2>Your activity</h2></div><label>Year<Select aria-label="Activity year" value={year} onChange={event=>{setYear(Number(event.target.value));setSelected('');}}>{years.map(value=><option key={value} value={value}>{value}</option>)}</Select></label></div>
    <div className={`activity-stats ${year!==currentYear?'activity-stats-historical':''}`}><div><strong>{summary.total.toLocaleString()}</strong><span>{summary.source?'submissions':'imported submissions'} in {year}</span></div><div><strong>{summary.accepted.toLocaleString()}</strong><span>accepted in imported details</span></div><div><strong>{summary.activeDays}</strong><span>{summary.source?'active days':'recorded active days'}</span></div>{year===currentYear&&<div><strong>{summary.current}</strong><span>current streak · {year}</span></div>}<div><strong>{summary.longest}</strong><span>longest streak in {year}</span></div></div>
    <p className="chart-note activity-reconciliation">{summary.source?<>LeetCode calendar: {summary.total.toLocaleString()} submissions. {summary.imported.toLocaleString()} individual submission details imported{summary.imported===summary.total?' — totals match.':`. ${Math.max(0,summary.total-summary.imported).toLocaleString()} details are not available in this import.`} Calendar refreshed {new Date(summary.observedAt!).toLocaleString()}.</>:<>Showing {summary.imported.toLocaleString()} imported submission details. LeetCode’s yearly calendar has not been imported; totals and streaks may be incomplete. Run a history update to reconcile them.</>}</p>
    <div className="activity-scroll"><div className="activity-calendar"><div className="activity-months">{cells.filter(day=>day.getUTCDate()<=7&&day.getUTCDay()===1).map(day=><span key={utcDay(day)} style={{gridColumn:Math.floor((day.getTime()-gridStart.getTime())/604800000)+1}}>{day.toLocaleDateString('en',{month:'short',timeZone:'UTC'})}</span>)}</div><div className="activity-grid">{cells.map(day=>{const key=utcDay(day),count=summary.counts[key]??0,inYear=day.getUTCFullYear()===year,level=count===0?0:count===1?1:count<=3?2:count<=7?3:4;return <button type="button" key={key} className={`activity-day activity-level-${level} ${selected===key?'selected':''} ${!inYear?'outside-year':''}`} disabled={!inYear} title={`${displayDay(key)}: ${count} submissions (UTC)`} aria-label={`${key}: ${count} submissions, ${summary.byDay[key]?.filter(accepted).length??0} accepted in imported details (UTC)`} aria-pressed={selected===key} onClick={()=>setSelected(key)} />;})}</div></div></div>
    <div className="activity-footer"><span>Each square uses LeetCode’s UTC day boundary. Select a day to inspect its submissions.</span><span>Less <i className="activity-level-0"/><i className="activity-level-1"/><i className="activity-level-2"/><i className="activity-level-3"/><i className="activity-level-4"/> More</span></div>
    {selected&&<div className="activity-detail"><div><h3>{displayDay(selected)}</h3><p>{dayTotal} submissions · {dayEntries.length} details imported · {dayEntries.filter(accepted).length} known accepted</p></div>{dayTotal>dayEntries.length&&<p>{dayTotal-dayEntries.length} submission details have not been imported for this day. The calendar total comes from LeetCode.</p>}{dayEntries.length?<ul>{dayEntries.map(submission=><li key={submission.id}><span className={accepted(submission)?'activity-accepted':'activity-other'}>{submission.status}</span><a href={worked.has(submission.slug)?`#/problem/${worked.get(submission.slug)}`:`https://leetcode.com/problems/${submission.slug}/`} target={worked.has(submission.slug)?undefined:'_blank'} rel="noreferrer">{submission.title}</a><small>{new Date(submission.timestamp).toLocaleTimeString([],{hour:'numeric',minute:'2-digit',timeZone:'UTC'})} UTC · {submission.language}</small><a href={`https://leetcode.com/submissions/detail/${submission.id}/`} target="_blank" rel="noreferrer">View submission ↗</a></li>)}</ul>:dayTotal===0&&<p>{summary.source?'No submissions reported by LeetCode on this day.':'No submission details imported for this day.'}</p>}</div>}
    <p className="chart-note">Activity and longest streak use the selected year. Accepted counts use individual results; LeetCode’s calendar does not provide verdicts. Undated completion snapshots contribute to coverage only.</p>
  </section>;
}
