import {useMemo,useRef,useState} from 'react';
import type {Dispatch,SetStateAction} from 'react';
import {analytics,membershipIndex,treemap,parseSubmissionExport,mergeHistory,breadcrumbs,accepted,type Curriculum,type Progress,type NodeStats} from '@pattern-atlas/core';
export function LeetCodeSummary({progress}:{progress:Progress}) {
 const history=progress.leetcode;if(!history)return null;
 const solved=new Set([...history.completions?.slugs??[],...Object.values(history.submissions).filter(accepted).map(s=>s.slug)]);
 return <section className="history-connect imported-summary" aria-label="Imported LeetCode progress"><div><p className="eyebrow">YOUR LEETCODE PROGRESS</p><h2>{solved.size.toLocaleString()} completed problems</h2><p>{Object.keys(history.submissions).length.toLocaleString()} dated submissions · {history.account}</p></div><a className="button primary" href="#leetcode-progress" onClick={e=>{e.preventDefault();document.getElementById('leetcode-progress')?.scrollIntoView({behavior:'smooth',block:'start'});}}>View coverage & freshness ↓</a></section>;
}
const label=(s:NodeStats)=>`${s.node.title}: ${s.solved} accepted, ${s.attempted} attempted, ${s.unseen} no recorded attempt, ${s.total} problems; ${s.visits} category entries; ${s.fresh} fresh, ${s.practiced-s.fresh} need refresh`;
export function ProgressDashboard({data,progress,setProgress,setToast}:{data:Curriculum;progress:Progress;setProgress:Dispatch<SetStateAction<Progress>>;setToast:(s:string)=>void}) {
  const [freshDays,setFreshDays]=useState(30),[metric,setMetric]=useState('coverage'),[scope,setScope]=useState(''),[depth,setDepth]=useState(1),[difficulty,setDifficulty]=useState(''),[level,setLevel]=useState(''),[query,setQuery]=useState(''),[period,setPeriod]=useState(0),[view,setView]=useState('treemap'),[selected,setSelected]=useState(''),[historyQuery,setHistoryQuery]=useState(''),[result,setResult]=useState(''),[limit,setLimit]=useState(50),[visitQuery,setVisitQuery]=useState('');
  const [importError,setImportError]=useState('');const input=useRef<HTMLInputElement>(null);
  const index=useMemo(()=>membershipIndex(data),[data]);
  const stats=useMemo(()=>analytics(data,progress,{scope:scope||undefined,freshDays,depth,difficulty,level,query,since:period?Date.now()-period*86400000:undefined},index),[data,progress,scope,depth,difficulty,level,query,period,index,freshDays]);
  const rects=useMemo(()=>treemap(stats.tiles.map(s=>s.total)),[stats.tiles]);
  const active=stats.tiles.find(s=>s.node.id===selected);
  const submissions=stats.submissions.filter(s=>(!historyQuery||`${s.title} ${s.slug} ${s.language}`.toLowerCase().includes(historyQuery.toLowerCase()))&&(!result||(result==='accepted'?accepted(s):!accepted(s))));
  const bySlug=useMemo(()=>new Map((data.catalog??data.problems).map(p=>[p.slug,p])),[data]);
  const visits=Object.entries(stats.pages).filter(([page])=>pageName(page).toLowerCase().includes(visitQuery.toLowerCase())).sort((a,b)=>b[1].count-a[1].count);
  function pageName(page:string){const [,kind,id]=page.split('/');return kind==='library'&&id?(data.nodes.find(n=>n.id===id)?.title??page):kind==='problem'?(data.problems.find(p=>p.id===id)?.title??page):({'/':'Overview','/library':'Pattern library','/catalog':'All problems','/progress':'Your progress','/about':'Curriculum notes','/review':'Practice deck'}[page]??page);}
  async function importHistory(file?:File){if(!file)return;try{if(file.size>10_000_000)throw new Error('Submission file is too large (maximum 10 MB).');const incoming=parseSubmissionExport(await file.text());mergeHistory(progress.leetcode,incoming);setProgress(p=>({...p,leetcode:mergeHistory(p.leetcode,incoming)}));setImportError('');setToast(`Merged ${Object.keys(incoming.submissions).length.toLocaleString()} submissions. Duplicate IDs were kept once.`);}catch(e){setImportError(e instanceof Error?e.message:'Could not import history.');}finally{if(input.current)input.current.value='';}}
  async function copyExporter(){try{const response=await fetch('/tools/leetcode-export.user.js');if(!response.ok)throw new Error();await navigator.clipboard.writeText(await response.text());setToast('Exporter copied. Paste it in the console on your signed-in LeetCode progress page.');}catch{setToast('Open Download script to copy the exporter manually.');}}
  return <div id="leetcode-progress" className="analytics-dashboard" style={{scrollMarginTop:90}}>
    <section className="history-connect"><div><p className="eyebrow">LEETCODE HISTORY</p><h2>{progress.leetcode?`Connected by import · ${progress.leetcode.account}`:'Bring your practice history'}</h2><p>{progress.leetcode?`${Object.keys(progress.leetcode.submissions).length.toLocaleString()} submissions saved${progress.leetcode.through?` · through ${progress.leetcode.through}`:''} · last export ${new Date(progress.leetcode.exportedAt).toLocaleString()}`:'Import submissions to see accepted problems across the entire curriculum.'}</p>{progress.leetcode&&<small>{progress.leetcode.complete?'Latest export reached the oldest available record.':'Latest export is a partial update. Previously imported records are kept.'}</small>}</div><button className="button primary" onClick={()=>input.current?.click()}>Import LeetCode history</button><input ref={input} className="sr-only" aria-label="LeetCode history file" type="file" accept="application/json,.json" onChange={e=>void importHistory(e.target.files?.[0])}/></section>
    {progress.leetcode?.completions&&<p className="chart-note completion-note">LeetCode reports {progress.leetcode.completions.slugs.length} completed problems as of {new Date(progress.leetcode.completions.observedAt).toLocaleDateString()}. This snapshot contributes to all-time accepted coverage. Older submission dates may be unavailable; the snapshot does not refresh practice or create diagnostic ratings.{period>0?' Date-filtered coverage uses dated submissions only.':''}</p>}
    {importError&&<p role="alert" className="import-error">{importError}</p>}
    <details className="export-instructions"><summary>Export or update from LeetCode</summary><ol><li>Open <a href="https://leetcode.com/progress/" target="_blank" rel="noreferrer">your LeetCode progress page</a> on a desktop browser, signed in.</li><li>Copy the exporter below, open the browser’s developer console (⌘⌥J on Chrome for Mac; Ctrl+Shift+J on Windows), and paste the script. Review it before running.</li><li>Choose <strong>Export all available history</strong> the first time, or <strong>Update · last 30 days</strong> for regular refreshes. Use a full export after longer gaps.</li><li>Import the downloaded JSON here or in iOS. Reimporting is safe: submission IDs are merged once.</li></ol><div className="button-row"><button className="button secondary" onClick={copyExporter}>Copy exporter script</button><a className="button secondary" href="/tools/leetcode-export.user.js" download>Download script</a></div><p>For unattended updates, use the repository’s headless commands: npm run history:login once, then npm run history:export. The same script can be installed in a userscript manager to keep an export button on LeetCode. It reads only submission metadata; passwords, cookies, and solution code stay out of the export. No automatic background sync.</p></details>
    <section className="stats-row" aria-label="Submission statistics"><div><strong>{stats.solved}</strong><span>accepted problems</span></div><div><strong>{stats.attempted}</strong><span>attempted, no acceptance</span></div><div><strong>{stats.scopeProblems.length}</strong><span>problems in scope</span></div><div><strong>{Object.values(stats.pages).reduce((s,v)=>s+v.count,0)}</strong><span>page entries · all time</span></div></section>
    <section className="refocus-panel"><div className="section-heading"><div><p className="eyebrow">WHERE TO REFOCUS</p><h2>Keep the patterns fresh</h2></div><label>Refresh after<select aria-label="Freshness window" value={freshDays} onChange={e=>setFreshDays(Number(e.target.value))}>{[7,14,30,60,90].map(d=><option key={d} value={d}>{d} days</option>)}</select></label></div><p className="chart-note">Fresh = practiced within {freshDays} days through a submission or recall review. Page visits do not count. Suggestions prioritize due reviews, then previously practiced problems that need refreshing, then coverage gaps. This is a practice signal, not a mastery score.</p><div className="refocus-grid">{stats.focus.map(s=><a key={s.node.id} href={`#/library/${s.node.id}`}><strong>{s.node.title}</strong><span className="freshness-number">{Math.round(s.fresh/s.total*100)}% fresh</span><span>{s.due>0?`${s.due} reviews due · `:''}{s.practiced-s.fresh} need refresh · {s.total-s.practiced} no dated practice</span><small>{s.lastPracticed?`Last practiced ${new Date(s.lastPracticed).toLocaleDateString()}`:'No practice recorded'} · {s.solved}/{s.total} accepted</small></a>)}</div>{!stats.focus.length&&<p>No patterns need refreshing in this scope.</p>}</section>
    <section className="progress-explorer"><div className="section-heading"><div><p className="eyebrow">CURRICULUM COVERAGE</p><h2>Explore your progress</h2></div><div className="chart-switch" role="group" aria-label="Chart view">{['treemap','bars'].map(v=><button key={v} aria-pressed={view===v} onClick={()=>setView(v)}>{v==='treemap'?'Treemap':'Stacked bars'}</button>)}</div></div>
      <div className="analytics-filters"><label>Chart metric<select value={metric} onChange={e=>setMetric(e.target.value)}><option value="coverage">Accepted coverage</option><option value="freshness">Practice freshness</option></select></label><label>Category<select value={scope} onChange={e=>{setScope(e.target.value);setSelected('');}}><option value="">Entire curriculum</option>{data.nodes.filter(n=>n.kind==='category').map(n=><option key={n.id} value={n.id}>{breadcrumbs(data.nodes,n.id).map(x=>x.title).join(' / ')}</option>)}</select></label><label>Aggregation<select aria-label="Aggregation" value={depth} onChange={e=>setDepth(Number(e.target.value))}><option value={1}>Next level</option><option value={2}>2 levels down</option><option value={3}>3 levels down</option><option value={99}>All leaves</option></select></label><label>Problem difficulty<select value={difficulty} onChange={e=>setDifficulty(e.target.value)}><option value="">All difficulties</option>{['Easy','Medium','Hard'].map(x=><option key={x}>{x}</option>)}</select></label><label>Pattern level<select value={level} onChange={e=>setLevel(e.target.value)}><option value="">All levels</option>{['Foundation','Intermediate','Advanced'].map(x=><option key={x}>{x}</option>)}</select></label><label>Submission period<select value={period} onChange={e=>setPeriod(Number(e.target.value))}><option value={0}>All imported history</option><option value={30}>Last 30 days</option><option value={90}>Last 90 days</option></select></label><label>Find a tile<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Category or pattern name"/></label></div>
      <div className="chart-breadcrumb"><button onClick={()=>setScope('')}>All topics</button>{scope&&breadcrumbs(data.nodes,scope).map(n=><button key={n.id} onClick={()=>setScope(n.id)}> / {n.title}</button>)}</div>
      <div className="chart-legend"><span><i className="accepted-fill"/>{metric==='coverage'?'Accepted':'Fresh'}</span><span><i className="attempted-fill"/>{metric==='coverage'?'Attempted without acceptance':'Needs refresh'}</span><span><i className="unseen-fill"/>{metric==='coverage'?'No recorded attempt':'No dated practice'}</span></div>
      <p className="chart-note">Area represents problem memberships. Blue fill shows the selected metric. Freshness always uses all recorded practice, independent of the submission-period filter. Problems can appear in multiple tiles; overall totals count each problem once. Acceptance in a pattern means its problems were solved, not that this technique was used.{period>0&&` Results use only submissions from the last ${period} days.`}</p>
      {!stats.tiles.length?<p className="empty-chart">No categories match these filters.</p>:view==='treemap'?<div className="treemap" aria-label="Problem coverage treemap">{rects.map(r=>{const s=stats.tiles[r.index],small=r.width<115||r.height<65;return <button key={s.node.id} className={`treemap-tile ${selected===s.node.id?'selected':''} ${small?'compact':''}`} aria-label={label(s)} title={label(s)} style={{left:`${r.x/10}%`,top:`${r.y/5.6}%`,width:`${r.width/10}%`,height:`${r.height/5.6}%`}} onClick={()=>setSelected(s.node.id)}><span className="tile-progress" style={{height:`${(metric==='coverage'?s.solved:s.fresh)/s.total*100}%`}}/><span className="tile-copy"><strong>{s.node.title}</strong><span>{metric==='coverage'?s.solved:s.fresh} / {s.total}{metric==='freshness'?' fresh':''}</span>{!small&&<small>{s.visits} entries</small>}</span></button>;})}</div>:<div className="stacked-chart" aria-label="Stacked category progress">{stats.tiles.map(s=><button key={s.node.id} onClick={()=>setSelected(s.node.id)} aria-label={label(s)}><strong>{s.node.title}</strong><span className="stacked-track"><i className="accepted-fill" style={{width:`${100*(metric==='coverage'?s.solved:s.fresh)/s.total}%`}}/><i className="attempted-fill" style={{width:`${100*(metric==='coverage'?s.attempted:s.practiced-s.fresh)/s.total}%`}}/><i className="unseen-fill" style={{width:`${100*(metric==='coverage'?s.unseen:s.total-s.practiced)/s.total}%`}}/></span><span>{metric==='coverage'?s.solved:s.fresh} / {s.total}{metric==='freshness'?' fresh':''}</span></button>)}</div>}
      {active&&<div className="tile-detail" role="status"><div><h3>{active.node.title}</h3><p>{active.solved} accepted · {active.attempted} attempted · {active.unseen} no recorded attempt</p><p>{active.fresh} fresh · {active.practiced-active.fresh} need refresh · {active.total-active.practiced} no dated practice</p><small>{active.visits} category entries, including child pages · {active.node.level}</small></div><div className="button-row">{data.nodes.some(n=>n.parentId===active.node.id)&&<button className="button secondary" onClick={()=>{setScope(active.node.id);setSelected('');}}>Drill into category</button>}<a className="button primary" href={`#/library/${active.node.id}`}>Open study page</a></div></div>}
      <details className="chart-data"><summary>View all {stats.tiles.length} tiles as a table</summary><div className="analytics-table-scroll"><table><thead><tr><th>Category / pattern</th><th>Accepted</th><th>Attempted</th><th>Total</th><th>Fresh</th><th>Entries</th></tr></thead><tbody>{stats.tiles.map(s=><tr key={s.node.id}><td><a href={`#/library/${s.node.id}`}>{s.node.title}</a></td><td>{s.solved}</td><td>{s.attempted}</td><td>{s.total}</td><td>{s.fresh}</td><td>{s.visits}</td></tr>)}</tbody></table></div></details>
    </section>
    <section className="submission-history"><div className="section-heading"><h2>Submission history</h2><span>{submissions.length.toLocaleString()} records</span></div><div className="analytics-filters"><label>Search submissions<input placeholder="Problem or language" value={historyQuery} onChange={e=>{setHistoryQuery(e.target.value);setLimit(50);}}/></label><label>Result<select value={result} onChange={e=>{setResult(e.target.value);setLimit(50);}}><option value="">All results</option><option value="accepted">Accepted</option><option value="other">Other results</option></select></label></div><p className="chart-note">Uses the category, difficulty, and submission period above. {stats.unmapped>0&&`${stats.unmapped} imported records have no match in this catalog; they remain in unfiltered history.`}</p><div className="analytics-table-scroll"><table><thead><tr><th>Submitted</th><th>Problem</th><th>Result</th><th>Language</th><th>LeetCode</th></tr></thead><tbody>{submissions.slice(0,limit).map(s=>{const p=bySlug.get(s.slug),local=p&&data.problems.some(x=>x.id===p.id);return <tr key={s.id}><td><time dateTime={s.timestamp}>{new Date(s.timestamp).toLocaleString()}</time></td><td><a href={local?`#/problem/${p.id}`:`https://leetcode.com/problems/${s.slug}/`} target={local?undefined:'_blank'} rel="noreferrer">{p?`${p.id}. `:''}{s.title}</a></td><td><span className={`submission-result ${accepted(s)?'is-accepted':''}`}>{s.status}</span></td><td>{s.language}</td><td><a href={`https://leetcode.com/submissions/detail/${s.id}/`} target="_blank" rel="noreferrer">View ↗</a></td></tr>;})}</tbody></table></div>{!submissions.length&&<p className="empty-chart">{progress.leetcode?'No submissions match these filters.':'Import a LeetCode export to populate your history.'}</p>}{submissions.length>limit&&<button className="button secondary" onClick={()=>setLimit(limit+100)}>Show more submissions</button>}</section>
    <section className="page-visits"><div className="section-heading"><h2>Page entries</h2><span>All time · this workspace</span></div><p className="chart-note">Counted when a page opens or you navigate back to it. Editing, revealing solutions, and changing filters do not add entries. Counts begin with this update and are included in backups.</p><label className="visit-search">Find a page<input value={visitQuery} onChange={e=>setVisitQuery(e.target.value)} placeholder="Page or pattern name"/></label><div className="analytics-table-scroll visit-table"><table><thead><tr><th>Page</th><th>Entries</th><th>Last opened</th></tr></thead><tbody>{visits.map(([page,v])=><tr key={page}><td><a href={`#${page}`}>{pageName(page)}</a><small>{page}</small></td><td>{v.count}</td><td>{new Date(v.lastVisited).toLocaleString()}</td></tr>)}</tbody></table></div></section>
  </div>;
}
