import {Select} from './Select';
import {MultiSelect} from './MultiSelect';
import {ActivityHeatmap} from './ActivityHeatmap';
import {TileTooltip} from './TileTooltip';
import {useMemo,useRef,useState} from 'react';
import type {Dispatch,SetStateAction} from 'react';
import {analytics,membershipIndex,hierarchicalTreemap,parseSubmissionExport,mergeHistory,breadcrumbs,accepted,practiceRecommendations,type Curriculum,type Progress,type NodeStats,type HistoryPeriod} from '@pattern-atlas/core';
export function LeetCodeSummary({progress}:{progress:Progress}) {
 const history=progress.leetcode;if(!history)return null;
 const solved=new Set([...history.completions?.slugs??[],...Object.values(history.submissions).filter(accepted).map(s=>s.slug)]);
 return <section className="history-connect imported-summary" aria-label="Imported LeetCode progress"><div><p className="eyebrow">YOUR LEETCODE PROGRESS</p><h2>{solved.size.toLocaleString()} completed problems</h2><p>{Object.keys(history.submissions).length.toLocaleString()} dated submissions · {history.account}</p></div><a className="button primary" href="#leetcode-progress" onClick={e=>{e.preventDefault();document.getElementById('leetcode-progress')?.scrollIntoView({behavior:'smooth',block:'start'});}}>View coverage & freshness ↓</a></section>;
}
const label=(s:NodeStats)=>`${s.node.title}: ${s.solved} accepted, ${s.attempted} attempted, ${s.unseen} no recorded attempt, ${s.total} problems; ${s.visits} category entries; ${s.fresh} fresh, ${s.practiced-s.fresh} need refresh`;
const historyPeriods:{value:HistoryPeriod;label:string}[]=[{value:'recent',label:'Last 30 days'},{value:'middle',label:'31–90 days ago'},{value:'older',label:'Over 90 days ago'}];
export function ProgressDashboard({data,progress,setProgress,setToast}:{data:Curriculum;progress:Progress;setProgress:Dispatch<SetStateAction<Progress>>;setToast:(s:string)=>void}) {
  const [freshDays,setFreshDays]=useState(30),[metric,setMetric]=useState('coverage'),[scopes,setScopes]=useState<string[]>([]),[depth,setDepth]=useState(1),[difficulties,setDifficulties]=useState<string[]>([]),[levels,setLevels]=useState<string[]>([]),[query,setQuery]=useState(''),[periods,setPeriods]=useState<HistoryPeriod[]>([]),[view,setView]=useState('treemap'),[selected,setSelected]=useState(''),[historyQuery,setHistoryQuery]=useState(''),[result,setResult]=useState(''),[limit,setLimit]=useState(50),[visitQuery,setVisitQuery]=useState('');
  const [importError,setImportError]=useState('');const input=useRef<HTMLInputElement>(null);
  const index=useMemo(()=>membershipIndex(data),[data]);
  const categoryOptions=useMemo(()=>data.nodes.filter(n=>n.kind==='category').map(n=>({value:n.id,label:breadcrumbs(data.nodes,n.id).map(x=>x.title).join(' / ')})),[data]);
  const stats=useMemo(()=>analytics(data,progress,{scope:scopes,freshDays,depth,difficulty:difficulties,level:levels,query,periods},index),[data,progress,scopes,depth,difficulties,levels,query,periods,index,freshDays]);
  const recommendations=useMemo(()=>practiceRecommendations(data,progress,{scope:scopes,difficulty:difficulties,level:levels,freshDays}),[data,progress,scopes,difficulties,levels,freshDays]);
  const layout=useMemo(()=>hierarchicalTreemap(stats.tiles,data.nodes),[stats.tiles,data.nodes]);
  const active=stats.tiles.find(s=>s.node.id===selected);
  const submissions=stats.submissions.filter(s=>(!historyQuery||`${s.title} ${s.slug} ${s.language}`.toLowerCase().includes(historyQuery.toLowerCase()))&&(!result||(result==='accepted'?accepted(s):!accepted(s))));
  const bySlug=useMemo(()=>new Map((data.catalog??data.problems).map(p=>[p.slug,p])),[data]);
  const visits=Object.entries(stats.pages).filter(([page])=>pageName(page).toLowerCase().includes(visitQuery.toLowerCase())).sort((a,b)=>b[1].count-a[1].count);
  function pageName(page:string){const [,kind,id]=page.split('/');return kind==='library'&&id?(data.nodes.find(n=>n.id===id)?.title??page):kind==='problem'?(data.problems.find(p=>p.id===id)?.title??page):({'/':'Overview','/library':'Pattern library','/catalog':'All problems','/progress':'Your progress','/about':'Curriculum notes','/review':'Practice deck'}[page]??page);}
  async function importHistory(file?:File){if(!file)return;try{if(file.size>10_000_000)throw new Error('Submission file is too large (maximum 10 MB).');const incoming=parseSubmissionExport(await file.text());mergeHistory(progress.leetcode,incoming);setProgress(p=>({...p,leetcode:mergeHistory(p.leetcode,incoming)}));setImportError('');setToast(`Merged ${Object.keys(incoming.submissions).length.toLocaleString()} submissions. Duplicate IDs were kept once.`);}catch(e){setImportError(e instanceof Error?e.message:'Could not import history.');}finally{if(input.current)input.current.value='';}}
  async function copyExporter(){try{const response=await fetch('/tools/leetcode-export.user.js');if(!response.ok)throw new Error();await navigator.clipboard.writeText(await response.text());setToast('Exporter copied. Paste it in the console on your signed-in LeetCode progress page.');}catch{setToast('Open Download script to copy the exporter manually.');}}
  return <div id="leetcode-progress" className="analytics-dashboard" style={{scrollMarginTop:90}}>
    <section className="progress-explorer"><div className="section-heading"><div><p className="eyebrow">CURRICULUM COVERAGE</p><h2>Explore your progress</h2></div><div className="chart-switch" role="group" aria-label="Chart view">{['treemap','bars'].map(v=><button key={v} aria-pressed={view===v} onClick={()=>setView(v)}>{v==='treemap'?'Treemap':'Stacked bars'}</button>)}</div></div>
      <div className="analytics-filters">
        <label>Chart metric<Select aria-label="Chart metric" value={metric} onChange={e=>setMetric(e.target.value)}><option value="coverage">Accepted coverage</option><option value="freshness">Practice freshness</option></Select></label>
        <label>Category<MultiSelect label="Category" allLabel="Entire curriculum" options={categoryOptions} value={scopes} onChange={values=>{setScopes(values);setSelected('');}} searchable/></label>
        <label>Map detail<Select aria-label="Map detail" value={depth} onChange={e=>setDepth(Number(e.target.value))}><option value={1}>Overview</option><option value={2}>Grouped detail</option><option value={3}>Fine detail</option><option value={99}>All patterns &amp; collections</option></Select></label>
        <label>Problem difficulty<MultiSelect label="Problem difficulty" allLabel="All difficulties" options={['Easy','Medium','Hard'].map(x=>({value:x,label:x}))} value={difficulties} onChange={setDifficulties}/></label>
        <label>Pattern level<MultiSelect label="Pattern level" allLabel="All levels" options={['Foundation','Intermediate','Advanced'].map(x=>({value:x,label:x}))} value={levels} onChange={setLevels}/></label>
        <label>Submission period<MultiSelect label="Submission period" allLabel="All imported history" options={historyPeriods} value={periods} onChange={values=>setPeriods(values as HistoryPeriod[])}/></label>
        <label>Find a tile<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Category or pattern name"/></label>
      </div>
      <div className="chart-breadcrumb"><button onClick={()=>setScopes([])}>All topics</button>{scopes.map(id=><button key={id} onClick={()=>setScopes(scopes.filter(x=>x!==id))}> / {data.nodes.find(n=>n.id===id)?.title??id} ×</button>)}</div>
      <div className="chart-legend"><span><i className="accepted-fill"/>{metric==='coverage'?'Accepted':'Fresh'}</span><span><i className="attempted-fill"/>{metric==='coverage'?'Attempted without acceptance':'Needs refresh'}</span><span><i className="unseen-fill"/>{metric==='coverage'?'No recorded attempt':'No dated practice'}</span></div>
      <p className="chart-note">Tile area reflects problem memberships; labeled borders keep related categories together. Select multiple categories, difficulties, levels, or date ranges to compare them. Blue fill shows the selected metric. Freshness uses all recorded practice. Problems can appear in multiple tiles; overall totals count each problem once. Acceptance in a pattern means its problems were solved, not that this technique was used.{periods.length>0&&' Date-filtered coverage uses only submissions from the selected ranges.'}</p>
      {!stats.tiles.length?<p className="empty-chart">No categories match these filters.</p>:view==='treemap'?<div className={`treemap ${depth===99?'deep-map':''}`} aria-label="Problem coverage treemap">
        {layout.groups.map(group=><div key={group.id} className={`treemap-group group-depth-${Math.min(group.depth,3)}`} data-group-id={group.id} aria-hidden="true" style={{left:`${group.x/10}%`,top:`${group.y/5.6}%`,width:`${group.width/10}%`,height:`${group.height/5.6}%`}}>{group.width>120&&group.height>95&&<span>{group.title}</span>}</div>)}
        {layout.tiles.map(r=>{const s=stats.tiles[r.index],small=r.width<115||r.height<65;return <TileTooltip key={s.node.id} stats={s} data={data}><a className={`treemap-tile ${selected===s.node.id?'selected':''} ${small?'compact':''}`} aria-label={`${label(s)}. Open problems in a new tab`} href={`/#/library/${s.node.id}?problems=1`} target="_blank" rel="noopener noreferrer" style={{left:`${r.x/10}%`,top:`${r.y/5.6}%`,width:`${r.width/10}%`,height:`${r.height/5.6}%`}} onClick={()=>setSelected(s.node.id)}><span className="tile-progress" style={{height:`${(metric==='coverage'?s.solved:s.fresh)/s.total*100}%`}}/><span className="tile-copy"><strong>{s.node.title}</strong><span>{metric==='coverage'?s.solved:s.fresh} / {s.total}{metric==='freshness'?' fresh':''}</span>{!small&&<small>{s.visits} entries</small>}</span></a></TileTooltip>;})}</div>:<div className="stacked-chart" aria-label="Stacked category progress">{stats.tiles.map(s=><a key={s.node.id} href={`/#/library/${s.node.id}?problems=1`} target="_blank" rel="noopener noreferrer" onClick={()=>setSelected(s.node.id)} aria-label={`${label(s)}. Open problems in a new tab`}><strong>{s.node.title}</strong><span className="stacked-track"><i className="accepted-fill" style={{width:`${100*(metric==='coverage'?s.solved:s.fresh)/s.total}%`}}/><i className="attempted-fill" style={{width:`${100*(metric==='coverage'?s.attempted:s.practiced-s.fresh)/s.total}%`}}/><i className="unseen-fill" style={{width:`${100*(metric==='coverage'?s.unseen:s.total-s.practiced)/s.total}%`}}/></span><span>{metric==='coverage'?s.solved:s.fresh} / {s.total}{metric==='freshness'?' fresh':''}</span></a>)}</div>}
      {active&&<div className="tile-detail" role="status"><div><h3>{active.node.title}</h3><p>{active.solved} accepted · {active.attempted} attempted · {active.unseen} no recorded attempt</p><p>{active.fresh} fresh · {active.practiced-active.fresh} need refresh · {active.total-active.practiced} no dated practice</p><small>{active.visits} category entries, including child pages · {active.node.level}</small></div><div className="button-row">{data.nodes.some(n=>n.parentId===active.node.id)&&<button className="button secondary" onClick={()=>{setScopes([active.node.id]);setSelected('');}}>Drill into category</button>}<a className="button primary" href={`/#/library/${active.node.id}?problems=1`} target="_blank" rel="noopener noreferrer">Open problems ↗</a></div></div>}
      <details className="chart-data"><summary>View all {stats.tiles.length} tiles as a table</summary><div className="analytics-table-scroll"><table><thead><tr><th>Category / pattern</th><th>Accepted</th><th>Attempted</th><th>Total</th><th>Fresh</th><th>Entries</th></tr></thead><tbody>{stats.tiles.map(s=><tr key={s.node.id}><td><a href={`#/library/${s.node.id}`}>{s.node.title}</a></td><td>{s.solved}</td><td>{s.attempted}</td><td>{s.total}</td><td>{s.fresh}</td><td>{s.visits}</td></tr>)}</tbody></table></div></details>
    </section>
    <ActivityHeatmap data={data} progress={progress}/>
    <section className="history-connect"><div><p className="eyebrow">LEETCODE HISTORY</p><h2>{progress.leetcode?`Connected by import · ${progress.leetcode.account}`:'Bring your practice history'}</h2><p>{progress.leetcode?`${Object.keys(progress.leetcode.submissions).length.toLocaleString()} submissions saved${progress.leetcode.through?` · through ${progress.leetcode.through}`:''} · last export ${new Date(progress.leetcode.exportedAt).toLocaleString()}`:'Import submissions to see accepted problems across the entire curriculum.'}</p>{progress.leetcode&&<small>{progress.leetcode.complete?'Latest export reached the oldest available record.':'Latest export is a partial update. Previously imported records are kept.'}</small>}</div><button className="button primary" onClick={()=>input.current?.click()}>Import LeetCode history</button><input ref={input} className="sr-only" aria-label="LeetCode history file" type="file" accept="application/json,.json" onChange={e=>void importHistory(e.target.files?.[0])}/></section>
    {progress.leetcode?.completions&&<p className="chart-note completion-note">LeetCode reports {progress.leetcode.completions.slugs.length} completed problems as of {new Date(progress.leetcode.completions.observedAt).toLocaleDateString()}. This snapshot contributes to all-time accepted coverage. Older submission dates may be unavailable; the snapshot does not refresh practice or create diagnostic ratings.{periods.length?' Date-filtered coverage uses dated submissions only.':''}</p>}
    {importError&&<p role="alert" className="import-error">{importError}</p>}
    <details className="export-instructions"><summary>Export or update from LeetCode</summary><ol><li>Open <a href="https://leetcode.com/progress/" target="_blank" rel="noreferrer">your LeetCode progress page</a> on a desktop browser, signed in.</li><li>Copy the exporter below, open the browser’s developer console (⌘⌥J on Chrome for Mac; Ctrl+Shift+J on Windows), and paste the script. Review it before running.</li><li>Choose <strong>Export all available history</strong> the first time, or <strong>Update · last 30 days</strong> for regular refreshes. Use a full export after longer gaps.</li><li>Import the downloaded JSON here or in iOS. Reimporting is safe: submission IDs are merged once.</li></ol><div className="button-row"><button className="button secondary" onClick={copyExporter}>Copy exporter script</button><a className="button secondary" href="/tools/leetcode-export.user.js" download>Download script</a></div><p>For unattended updates, use the repository’s headless commands: npm run history:login once, then npm run history:export. The same script can be installed in a userscript manager to keep an export button on LeetCode. It reads only submission metadata; passwords, cookies, and solution code stay out of the export. Connected apps synchronize imported history, but LeetCode scraping runs only when you start an update.</p></details>
    <section className="stats-row" aria-label="Submission statistics"><div><strong>{stats.solved}</strong><span>accepted problems</span></div><div><strong>{stats.attempted}</strong><span>attempted, no acceptance</span></div><div><strong>{stats.scopeProblems.length}</strong><span>problems in scope</span></div><div><strong>{Object.values(stats.pages).reduce((s,v)=>s+v.count,0)}</strong><span>page entries · all time</span></div></section>
    <section className="refocus-panel" aria-label="Recommended practice">
      <div className="section-heading"><div><p className="eyebrow">YOUR NEXT SESSION</p><h2>Recommended practice</h2></div><label>Refresh after<Select aria-label="Freshness window" value={freshDays} onChange={e=>setFreshDays(Number(e.target.value))}>{[7,14,30,60,90].map(d=><option key={d} value={d}>{d} days</option>)}</Select></label></div>
      <p className="chart-note">{progress.leetcode?'Chosen from your LeetCode history and study activity.':'A starting set of worked patterns. Import your LeetCode history to personalize it.'} Due reviews and unsuccessful attempts come first, followed by uncertain solutions, older practice, and gaps. The set balances topics and avoids repeating a problem.</p>
      <div className="practice-grid">{recommendations.map((r,i)=><article className="practice-tile" key={r.node.id}>
        <div className="practice-tile-top"><span className="practice-reason">{r.kind}</span><span className="practice-rank">{String(i+1).padStart(2,'0')}</span></div>
        <p className="practice-topic">{r.topic} · {r.node.level}</p><h3><a href={`#/library/${r.node.id}`}>{r.node.title}</a></h3>
        <p className="practice-explanation">{r.reason}</p>
        <a className="practice-problem" href={`#/problem/${r.problem.id}?pattern=${r.node.id}`}><span>Practice #{r.problem.id} · {r.problem.difficulty}</span><strong>{r.problem.title} <span aria-hidden="true">→</span></strong></a>
      </article>)}</div>
      {!recommendations.length&&<p className="empty-chart">No practice is due for these filters. Broaden the category or difficulty to explore more patterns.</p>}
      <p className="practice-footnote">Uses the selected category, difficulty, and pattern level with all available history. Missing dates stay unknown. Completion is evidence of coverage, not mastery.</p>
    </section>
    <section className="submission-history"><div className="section-heading"><h2>Submission history</h2><span>{submissions.length.toLocaleString()} records</span></div><div className="analytics-filters"><label>Search submissions<input placeholder="Problem or language" value={historyQuery} onChange={e=>{setHistoryQuery(e.target.value);setLimit(50);}}/></label><label>Result<Select aria-label="Result" value={result} onChange={e=>{setResult(e.target.value);setLimit(50);}}><option value="">All results</option><option value="accepted">Accepted</option><option value="other">Other results</option></Select></label></div><p className="chart-note">Uses the category, difficulty, and submission period above. {stats.unmapped>0&&`${stats.unmapped} imported records have no match in this catalog; they remain in unfiltered history.`}</p><div className="analytics-table-scroll"><table><thead><tr><th>Submitted</th><th>Problem</th><th>Result</th><th>Language</th><th>LeetCode</th></tr></thead><tbody>{submissions.slice(0,limit).map(s=>{const p=bySlug.get(s.slug),local=p&&data.problems.some(x=>x.id===p.id);return <tr key={s.id}><td><time dateTime={s.timestamp}>{new Date(s.timestamp).toLocaleString()}</time></td><td><a href={local?`#/problem/${p.id}`:`https://leetcode.com/problems/${s.slug}/`} target={local?undefined:'_blank'} rel="noreferrer">{p?`${p.id}. `:''}{s.title}</a></td><td><span className={`submission-result ${accepted(s)?'is-accepted':''}`}>{s.status}</span></td><td>{s.language}</td><td><a href={`https://leetcode.com/submissions/detail/${s.id}/`} target="_blank" rel="noreferrer">View ↗</a></td></tr>;})}</tbody></table></div>{!submissions.length&&<p className="empty-chart">{progress.leetcode?'No submissions match these filters.':'Import a LeetCode export to populate your history.'}</p>}{submissions.length>limit&&<button className="button secondary" onClick={()=>setLimit(limit+100)}>Show more submissions</button>}</section>
    <section className="page-visits"><div className="section-heading"><h2>Page entries</h2><span>All time · this workspace</span></div><p className="chart-note">Counted when a page opens or you navigate back to it. Editing, revealing solutions, and changing filters do not add entries. Counts begin with this update and are included in backups.</p><label className="visit-search">Find a page<input value={visitQuery} onChange={e=>setVisitQuery(e.target.value)} placeholder="Page or pattern name"/></label><div className="analytics-table-scroll visit-table"><table><thead><tr><th>Page</th><th>Entries</th><th>Last opened</th></tr></thead><tbody>{visits.map(([page,v])=><tr key={page}><td><a href={`#${page}`}>{pageName(page)}</a><small>{page}</small></td><td>{v.count}</td><td>{new Date(v.lastVisited).toLocaleString()}</td></tr>)}</tbody></table></div></section>
  </div>;
}
