"""Generate an auditable inventory of expanded practice collections."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
data=json.loads((ROOT/'packages/content/curriculum.json').read_text())
community=json.loads((ROOT/'packages/content/community-solutions.json').read_text())
worked={p['id']:p for p in data['problems']}
by_id={n['id']:n for n in data['nodes']}
def trail(node):
    result=[node['title']]
    while node['parentId']:
        node=by_id[node['parentId']];result.append(node['title'])
    return ' / '.join(reversed(result))
lines=['# Expanded problem library','',
       'Snapshot: 2026-09-27. Generated by `python3 scripts/report_library.py`.','',
       '| Content | Count |','|---|---:|',
       f'| Indexed LeetCode problems | {len(data["catalog"]):,} |',
       f'| Problems with in-app Python solutions | {len(worked):,} |',
       '| Authored lessons with original summaries and checked examples | 193 |',
       f'| Additional community solution cards | {data["stats"]["communityProblems"]:,} |',
       f'| In-app solution variants (authored + community) | {sum(len(p["solutions"]) for p in worked.values()):,} |',
       '| Authored individual patterns | 200 |',
       '| Source-guide practice collections | 313 |',
       f'| All practice collections, including official topics and unclassified | {sum(n["kind"]=="collection" for n in data["nodes"])} |','',
       'Community code comes from [walkccc/LeetCode](https://github.com/walkccc/LeetCode), pinned at `'+community['commit']+'`, under the [MIT license](licenses/walkccc-MIT.txt). Original authored cards take precedence for overlapping problem IDs. Imported implementations are syntax-checked and hashed, not executed or claimed to pass a private judge. Four invalid upstream files are recorded in the importer artifact and excluded.','',
       'Every collection can be sorted by difficulty in either direction, numeric problem ID in either direction, or title. The sorting preference is stored per collection. Both apps show content availability and provide saved drafts and revealable code for local solution cards. Official statements and examples for community cards remain on LeetCode.','',
       'The source-guide groupings preserve all 2,732 distinct problem IDs in the pinned reference index. Membership reflects the guide, not a guarantee that an imported implementation follows the same technique. Official-topic collections are broader than individual patterns. Original pattern leaves include related practice from their surrounding guide sections, labeled accordingly.','',
       '## Collection inventory','',
       '| Hierarchy | Indexed problems | With local solutions | Source |','|---|---:|---:|---|']
for node in data['nodes']:
    if node['kind']!='collection':continue
    ids=node.get('problemIds',[])
    url=node['sourceUrls'][0] if node['sourceUrls'] else ''
    lines.append(f'| [{trail(node)}](https://blue-sea-0c03ac51e.3.azurestaticapps.net/#/library/{node["id"]}) | {len(ids)} | {sum(pid in worked for pid in ids)} | [Reference]({url}) |')
(ROOT/'docs/PROBLEM_LIBRARY.md').write_text('\n'.join(lines)+'\n')
